### ISSUE TITLE
Sequelize Incompatibility with pg@7.x

### ISSUE THREAD

**Issue by ammoradi** [avarona/generator-fullstack-webapp#1]
# Sequelize is incompatible with pg@7.x
I tried to use `upsert()` function to insert data on my table,
Everything was clear and right in my _model_ and _router_ but **Sequelize** gave me an error when i tried to insert data: 
**`UnhandledTypeError: Cannot read property '0' of undefined`**

I searched about this and found out this happened on some people because Sequelize doesn't support pg@7.x thoroughly

as sequelize official website mentioned: 
[#pg@7 is currently not supported](http://docs.sequelizejs.com/manual/installation/getting-started)

I think its better to use pg@6.x version but if you still want to use pg@7.x see this link to fix it :
[feat(dependency): Support pg version 7 #7888](https://github.com/sequelize/sequelize/pull/7888)

**Comment by avarona** [comment]
Thanks for the feedback! Downgraded to pg@6.4.0 which should solve the issue.
